syntax = "proto3";

package userservice;

import "google/protobuf/timestamp.proto";

option go_package = "pkg/userservice";

service UserService {
    rpc Create(CreateRequest) returns (CreateResponse);
    rpc Get(GetRequest) returns (GetResponse);
}

message CreateRequest {
    string nickname = 1;
    string password = 2;
}

message CreateResponse {
    int64 id = 1;
}

message User {
    int64 id = 1;
    string nickname = 2;
    google.protobuf.Timestamp registered_at = 3;
}

message GetRequest {
    int64 id = 1;
}

message GetResponse {
    User user = 1;
}
